# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: first_app_3_parul
  host: localhost
  username: postgres
  password: root
  port: 5432

# test:
#   <<: *default
#   database: first_app_test_parul
#   host: localhost
#   username: postgres
#   password: root
#   port: 5432